# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in `.github/workflows`
    # You don't need to specify `/.github/workflows` for `directory`. 
    # You can use `directory: "/"`.
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
        - "github actions"
    commit-message:
        prefix: "gh actions"
  
  # Updates for npm
  - package-ecosystem: "npm"
    directory: "/rootine"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    allow:
        - dependency-type: "direct"
    labels:
        - "npm dependencies"
    commit-message:
        prefix: "npm"
